// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPmkAs6JB9i0N8faspEeXnnL82CnV4P2E',
    appId: '1:430256087104:web:9e9af447cfcc80c1fabfa5',
    messagingSenderId: '430256087104',
    projectId: 'task-tracker-8ceb9',
    authDomain: 'task-tracker-8ceb9.firebaseapp.com',
    storageBucket: 'task-tracker-8ceb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmy_uN5mPol-b-goo5NW7WrlE-kSFxkEA',
    appId: '1:430256087104:android:76fdfeeeb33447e6fabfa5',
    messagingSenderId: '430256087104',
    projectId: 'task-tracker-8ceb9',
    storageBucket: 'task-tracker-8ceb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9yRVUqwxss4iH7c-T_UXxLg_RcxFZ6RE',
    appId: '1:430256087104:ios:77eff9c224329ddafabfa5',
    messagingSenderId: '430256087104',
    projectId: 'task-tracker-8ceb9',
    storageBucket: 'task-tracker-8ceb9.firebasestorage.app',
    iosBundleId: 'com.example.taskTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9yRVUqwxss4iH7c-T_UXxLg_RcxFZ6RE',
    appId: '1:430256087104:ios:77eff9c224329ddafabfa5',
    messagingSenderId: '430256087104',
    projectId: 'task-tracker-8ceb9',
    storageBucket: 'task-tracker-8ceb9.firebasestorage.app',
    iosBundleId: 'com.example.taskTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPmkAs6JB9i0N8faspEeXnnL82CnV4P2E',
    appId: '1:430256087104:web:74b60baf254b52a8fabfa5',
    messagingSenderId: '430256087104',
    projectId: 'task-tracker-8ceb9',
    authDomain: 'task-tracker-8ceb9.firebaseapp.com',
    storageBucket: 'task-tracker-8ceb9.firebasestorage.app',
  );
}
